on:
- push
- workflow_dispatch

env:
  FIRST_NAME: John
  LAST_NAME: McGovern

jobs:
  contexts_exploration:
    runs-on: ubuntu-latest
    steps:
    - name: Who is the actor?
      shell: pwsh
      run: |
        Write-Host -Object "The individual who triggered this workflow is: ${{ github.actor }}"
    - name: Which event triggered this workflow?
      shell: pwsh
      run: |
        Write-Host -Object "The event type that triggered this workflow execution is: ${{ github.event_name }}"
  env_vars_2:
    runs-on: ubuntu-latest
    steps:
    - name: Write new environment variable
      shell: pwsh
      run: |
        "DATABASE_NAME=$((New-Guid).Guid)" >> $env:GITHUB_ENV
        "FIRST_NAME=Simona" >> $env:GITHUB_ENV
        "LAST_NAME=Millham" >> $env:GITHUB_ENV
    - name: First Name, no local step variables
      shell: pwsh
      run: |
        Write-Host -Object "The name of the FIRST_NAME variable is: $env:FIRST_NAME"
    - name: Last name, no local step variables
      shell: pwsh
      run: |
        Write-Host -Object "The name of the LAST_NAME variable is: $env:LAST_NAME"
    - name: Database name
      shell: pwsh
      run: |
        Write-Host -Object "The name of my database is: $env:DATABASE_NAME"

  env_vars:
    env:
      FIRST_NAME: Billy
      LAST_NAME: Jones
    runs-on: ubuntu-latest
    steps:
    - name: First Name, no local step variables
      shell: pwsh
      run: |
        Write-Host -Object "The name of the FIRST_NAME variable is: $env:FIRST_NAME"
    - name: Last name, no local step variables
      shell: pwsh
      run: |
        Write-Host -Object "The name of the LAST_NAME variable is: $env:LAST_NAME"
