on:
- push
- workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - shell: pwsh
      run: |
        Write-Host -Object "The name of the FIRST_NAME variable is: $env:FIRST_NAME"
