on:
- push
- workflow_dispatch

env:
  FIRST_NAME: John
  LAST_NAME: McGovern

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - shell: pwsh
      run: |
        Write-Host -Object "The name of the FIRST_NAME variable is: $env:FIRST_NAME"
    - shell: pwsh
      run: |
        Write-Host -Object "The name of the LAST_NAME variable is: $env:LAST_NAME"
